- name: detect private ip and interface on all hosts
  hosts: all
  tasks:
    - name: set_fact | figure out private ip address and interface
      set_fact:
        private_ip: "{{ hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] }}"
        private_interface: "{{ hostvars[inventory_hostname]['ansible_' + item]['device'] }}"
      when:
        - hostvars[inventory_hostname]['ansible_' + item].ipv4 is defined
        - hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] | ipaddr(hostvars[inventory_hostname]['local_subnet'])
      with_items: "{{ ansible_interfaces }}"
        
- name: Setup IPSec VPN with strongswan on gateway
  hosts: local_gateway
  tasks:
    - name: set_fact | make a list of all clients machine's private ip address
      set_fact:
        clients_private_ip: "{{ clients_private_ip | default([]) + [hostvars[item]['private_ip']] }}"
      with_items: "{{ groups['clients'] }}"

    - name: install strongswan
      apt:
        name: strongswan
        cache_valid_time: 3600
        state: present
    
    - name: set net.ipv4.ip_forward to 1
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
    
    - name: write ipsec conf
      template:
        src: strongswan_conf.j2
        dest: /etc/ipsec.conf
      notify: reload ipsec  
    
    - name: write the vpn secrets file
      template:
        src: strongswan_secrets.j2
        dest: /etc/ipsec.secrets
      notify: reload ipsec

    - name: create updown.sh
      template:
        src: updown_sh.j2
        dest: /etc/strongswan.d/updown.sh
        mode: 0754
      notify: reload ipsec

  handlers:
    - name: reload ipsec
      shell:
        cmd: /usr/sbin/ipsec reload
      notify: restart ipsec  

    - name: restart ipsec
      systemd:
        name: ipsec
        state: restarted

- name: Add routes to remote subnet on clients machines
  hosts: clients
  tasks:
    - name: Capturing Existing netplan Configurations files list
      find:
        paths: /etc/netplan
        patterns: "*.yml,*.yaml"
      register: _netplan_configs
    - name: get netplan config file content
      slurp:
        src: "{{_netplan_configs['files'][0]['path']}}"
      register: remote_content_encoded
    - name: decode netplan config file content and convert from yaml to json
      set_fact:
        netplan_config_file_content: "{{ remote_content_encoded.content | b64decode | from_yaml }}"
    - name: append routes to netplan config file content
      set_fact:
        netplan_config_file_content: "{{ netplan_config_file_content | default({}) | combine({'network': {'ethernets': {private_interface: {'routes': route_to_add_on_clients }}}}, recursive=true) }}"
      vars:
        route_to_add_on_clients: [{"to": "{{remote_subnet}}", "via": "{{ hostvars['local_gateway']['private_ip'] }}"}]
    - name: replace netplan config file
      copy:
        content: "{{ netplan_config_file_content | to_nice_yaml }}"
        dest: "{{_netplan_configs['files'][0]['path']}}"
        backup: yes
        mode: 0644
        owner: root
        group: root
      notify: netplan apply
  
  handlers:
  - name: netplan apply
    shell:
      cmd: netplan apply
    async: 45
    poll: 0
